name: Publish Scripts
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          continue_on_error: false

  publish:
    name: Push Scripts to Game
    runs-on: ubuntu-latest
    needs: test
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    concurrency: ci-${{ github.ref }}
    environment:
      name: Game
      url: https://screeps.com/a/#!/room/shard1/E48S28
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Berlin"
          timezoneMacos: "Europe/Berlin"
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run deploy
        env:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
